### ISSUE TITLE
whether you can share the code to calculate dice score

### ISSUE THREAD

**Issue by daxuemi** [qiuhuaqi/midir#8]
Dear Professor! Thank you very much for sharing your outstanding work.  It seems that you haven't shared the code for  calculating dice score, which is not very convenient for beginners like me to quantitatively investigate the accuracy of image registration.  I wonder if you can consider publicly calculating dice score code, thank you!

**Comment by qiuhuaqi** [comment]
Hi there, thank you for the kind words! Very sorry for only seeing this issue now.
The code for calculating Dice overlap is actually provided here: https://github.com/qiuhuaqi/midir/blob/ea6e96e7df6d1f06cc2c69b1d4cb6c972b5c0d15/utils/metric.py#L196

I'm sure there are other more thoughtfully implemented Dice score code out there and hope you have found one!
